Repository GrantBirki/json-yaml-validate, pull requests merged in 2023-08, with the labels that each got.

#22 Add ajv formats
  README.md
  __tests__/functions/json-validator.test.js
  action.yml
  dist/index.js
  dist/index.js.map
  dist/licenses.txt
  package-lock.json
  package.json
  src/functions/json-validator.js
Labels: enhancement

#23 npm update
  dist/index.js
  dist/index.js.map
  package-lock.json
Labels: dependencies

#25 debug improvements
  __tests__/functions/exclude.test.js
  dist/index.js
  dist/index.js.map
  src/functions/exclude.js
  src/functions/json-validator.js
  src/functions/yaml-validator.js
Labels: enhancement

#28 fdir modifications
  dist/index1.js
  dist/licenses.txt
  docs/acceptance-test-results.txt
  package-lock.json
Labels: dependencies

#29 Update Docs
  README.md
  action.yml
Labels: documentation

#31 Add support for validating specified files
  README.md
  __tests__/functions/json-validator.test.js
  __tests__/functions/yaml-validator.test.js
  action.yml
  dist/index.js
  dist/index.js.map
  src/functions/json-validator.js
  src/functions/yaml-validator.js
Labels: enhancement

#26 JSON as YAML - Bug Fix
  __tests__/fixtures/yaml_as_json/mixture/good-json.json
  __tests__/fixtures/yaml_as_json/mixture/invalid-json.json
  __tests__/fixtures/yaml_as_json/mixture/yaml1.yaml
  __tests__/fixtures/yaml_as_json/mixture/yaml2.yml
  __tests__/functions/json-validator.test.js
  dist/index.js
  dist/index.js.map
  docs/acceptance-test-results.txt
  src/functions/json-validator.js
  src/functions/yaml-validator.js
Labels: bug

#33 Bug Fix: Report all errors, not just one
  __tests__/fixtures/real_world/challenges/challenge.yml
  __tests__/fixtures/schemas/challenge.json
  __tests__/functions/json-validator.test.js
  dist/index.js
  dist/index.js.map
  src/functions/json-validator.js
Labels: bug

#34 Support More JSON Schema Versions
  README.md
  __tests__/functions/json-validator.test.js
  action.yml
  dist/index.js
  dist/index.js.map
  src/functions/json-validator.js
Labels: bug, enhancement
