Repository GrantBirki/json-yaml-validate, pull requests merged in 2024-04, with the labels that each got.

#59 General Updates
  .github/workflows/codeql-analysis.yml
  .github/workflows/package-check.yml
  dist/index.js
  dist/index.js.map
  package-lock.json
  package.json
Labels: dependencies

#61 feat(ajv-custom-format): initial poc
  .github/workflows/acceptance-test.yml
  README.md
  __tests__/fixtures/json/custom_ajv_regexp_format/invalid.json
  __tests__/fixtures/json/custom_ajv_regexp_format/valid.json
  __tests__/fixtures/schemas/schema_with_custom_ajv_regexp_format.json
  __tests__/functions/json-validator.test.js
  action.yml
  dist/index.js
  dist/index.js.map
  src/functions/json-validator.js
Labels: enhancement

#62 node package updates
  dist/index.js
  dist/index.js.map
  package-lock.json
Labels: dependencies

#63 add `Custom Regex Formats` section to the documentation
  README.md
Labels: documentation
